### PR TITLE
Fix return type of emscripten_glfw_is_window_fullscreen

### PR DESCRIPTION
**Pull request by sbc100**
I'm trying to change the type of EM_BOOL and this is currently blocking that:
  https://github.com/emscripten-core/emscripten/pull/22155

### CODE REVIEW

**Review by ypujante — COMMENTED** [review]
I don't understand the change you are making. You are trying to get rid of EM_BOOL in emscripten, yet this PR changes `int` to `EM_BOOL`. What am I missing?

**Comment by ypujante** [comment]
The problem is that your fix is not changing include/GLFW/emscripten_glfw3.h where it is defined...

**Comment by ypujante** [comment]
@sbc100 I think I understand what you are doing (which you could have explained...)

You changed (but KEPT) the define from `int` to `bool`

But my code in `glfw3.cpp` is using `int` instead of using `EM_BOOL` and that causes the issue you are seeing...

I will patch it...

**Comment by sbc100** [comment]
Yeah its not important (to me) what the return type of this function is.. as long as the header and source agree.

**Comment by sbc100** [comment]
Would you mind sending a PR to emscripten to update the port? (or should I just do it as part of my PR?)

**Comment by ypujante** [comment]
@sbc100 I am already in the process... should take a few minutes

**Pull request merged**
